<<<<<<< HEAD
#spring.application.name=demo
=======
spring.application.name=demo
>>>>>>> aae08d83d8169ac5916fa657ee2f22d4f97420cb
spring.datasource.url=jdbc:postgresql://localhost:5433/academie
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=demo

# ? correspond à Docker
#spring.datasource.url=jdbc:postgresql://localhost:5432/pfe
#spring.datasource.username=postgres
#spring.datasource.password=1234

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#server.port=8082